name: slang
description: A sample command-line application.
version: 0.3.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  petitparser: ^6.1.0
  args: ^2.6.0
  dart_console: ^4.1.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
